version: '3.1'
services:
  test-host-vishal:
    image: mysql
    restart: always
    container_name: test-host-vishal
    environment:
      MYSQL_ROOT_PASSWORD: ${ProductionDBPassword}
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
  
  api:
    image: api-backend
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      MySqlUserName: root
      MySqlPassword: ${ProductionDBPassword}
      MysqlHost: test-host-vishal
    depends_on:
      - test-host-vishal
    ports:
        - 8093:8093
    volumes:
      - ./data:/var/lib/mysql
  
  
